[[pages]]
path = "dashboard.py"
name = "PÃ¡gina Inicial"
icon = "ğŸ "

[[pages]]
path = "pages/Macae_dashboard.py"
name = "SEMED MacaÃ©"
icon = "ğŸ“˜"

[[pages]]
path = "pages/Marica_dashboard.py"
name = "Codemar MaricÃ¡"
icon = "ğŸ“—"
